name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 20
      - name: Install dependencies
        run: npm i
      - name: Build the website
        run: npm run build -- --public-url https://cyntler.com
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: S3 Sync
        run: aws s3 sync --delete ./dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}
      - name: CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id=${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
